server:
    listen: :8000
    base_url: ""
    auth:
        user: ""
        pass: ""
remote:
    type: local
    url: ""
    user: ""
    pass: ""
    endpoint: ""
    region: ""
    bucket: ""
    access_key: ""
    secret_key: ""
    use_ssl: false
    local_path: ./data
security:
    master_key: CHANGE-THIS-TO-A-SECURE-32BYTE-KEY
storage:
    metadata_path: ""
    cache_dir: ""
access:
    token: mysecret
